openapi: 3.0.2
info:
  title: Raumbuchungs-API
  version: 0.1.0
  description: API für das Buchen und Verwalten von Besprechungsräumen in der NLB.

servers:
  - url: https://gravitee-01.test.k8s.i-lab.online/raumbuchungsapi
    description: Testumgebung
  - url: https://gravitee-01.dev.k8s.i-lab.online/raumbuchungsapi
    description: Entwicklungsumgebung

tags:
  - name: Locations
    description: Umfasst Standorte und Räume.
  - name: Bookings
    description: Raumbuchungen

paths:
  /buildings:
    description: Ressource für die Standorte an denen sich Besprechungsräume befinden. Nur lesende Zugriffe.
    get:
      description: Dieser Endpunkt liefert alle bestehenden Standorte zurück. Wurden Parameter übergeben, werden nur die Standorte zurückgeliefert auf die **alle** Kriterien zu treffen. Wenn es keine Standorte gibt, auf die die Filterkriterien zu treffen, wird ein 200er mit leerer Liste zurückgeliefert.
      tags:
        - Locations
      operationId: getBuildings
      parameters:
        - name: city
          description: Parameter um Standorte nach der Stadt zu filtern.
          in: query
          schema:
            type: string
        - name: name
          description: Parameter um Standorte nach dem Namen zu filtern.
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Erfolgreicher Zugriff
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Building"
              example:
                - id: 9221035d-8512-4706-aef5-c0a09efe160c
                  name: Friwall
                  address:
                    street: Friedrichswall 10
                    plz: "30159"
                    city: Hannover
                  rooms: ...
                - id: 3429e546-abc3-45d4-b8ad-552e3359e882
                  name: HBA 11
                  address:
                    street: Hans-Böckler-Allee 11
                    plz: "30173"
                    city: Hannover
                  rooms: ...
    post:
      description: Legt einen neuen Standort an und liefert das vollständige Standort-Objekt zurück.
      tags:
        - Locations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuildingWrite'
      responses:
        '200':
          description: Neuer Standort wurde erfolgreich angelegt. Vollständiges Standort-Objekt befindet sich in der Antwort.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
        '400':
          description: Fehlerhafte Eingabedaten.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /buildings/{id}:
    description: Ressource eines einzelnen Standortes. Lesender und schreibender Zugriff.
    parameters:
      - name: id
        in: path
        required: true
        description: ID des Standortes.
        schema:
          type: string
          pattern: "^[a-z0-9-]{3,}$"
          example: friwall10
    get:
      description: Liefert einen Standort zurück.
      tags:
        - Locations
      operationId: getBuilding
      responses:
        '200':
          description: Erfolgreicher Zugriff auf den Standort.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
        '404':
          description: Kein Standort mit dieser Id vorhanden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Ändert die Daten des Standortes unter dieser Id.
      tags:
        - Locations
      operationId: updateBuilding
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuildingWrite'
      responses:
        '200':
          description: Standort wurde geändert. Die neuen Daten werden in der Payload mitgeliefert.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
        '400':
          description: Fehlerhafte Eingabedaten.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Kein Standort mit dieser Id vorhanden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Löscht den Standort unter dieser Id.
      tags:
        - Locations
      operationId: deleteBuilding
      responses:
        '204':
          description: Standort wurde gelöscht.
        '404':
          description: Kein Standort mit dieser Id vorhanden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:

    Building:
      description: Standorte an denen sich Besprechungsräume befinden können.
      type: object
      required:
        - id
        - name
        - address
        - rooms
      properties:
        id:
          type: string
          description: UUID des Standortes.
        name:
          type: string
          description: Name des Standortes.
        address:
         $ref: '#/components/schemas/Address'
        rooms:
          type: array
          description: Besprechungsräume des Standortes
          items:
            $ref: "#/components/schemas/TBD"
      example:
        id: 9221035d-8512-4706-aef5-c0a09efe160c
        name: Friwall
        address:
          street: Friedrichswall 10
          plz: "30159"
          city: Hannover
        rooms: ...

    BuildingWrite:
      description: Objekt für die Änderung eines Standortes
      type: object
      required:
        - name
        - address
      properties:
        name:
          type: string
          description: Name des Standortes.
        address:
          $ref: '#/components/schemas/Address'
      example:
        name: Friwall
        address:
          street: Friedrichswall 10
          plz: "30159"
          city: Hannover

    Address:
      type: object
      description: Postalische Anschrift des Standortes
      required:
        - street
        - plz
        - city
      properties:
        street:
          type: string
          description: Straße und Hausnummer
        plz:
          type: string
          pattern: "^[0-9]{5}$"
          description: PLZ der Adresse
        city:
          type: string
          description: Stadt

    TBD:
      description: TDB

    Error:
      description: Fehler
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: HTTP Status Code
        message:
          type: string
          description: Fehlermeldung
      example:
        code: 404
        message: Objekt mit id xyz existiert nicht.